* PART 2
- https://www.udacity.com/course/machine-learning-for-trading--ud501
There are ten secions in Part 2

* 02-01 - So you want to be a hedge fund manager
MC2: Computational Investing

Lessons: In this mini-course, we focus on modeling the behavior of stock markets.
- So you want to be a hedge fund manager?
- Market mechanics
- What is a company worth?
- The Capital Assets Pricing Model (CAPM)
- How hedge funds use the CAPM
- Technical Analysis
- Dealing with data
- Efficient Markets Hypothesis
- The Fundamental Law of active portfolio management
- Portfolio optimization and the efficient frontier

Projects:
- Build a market simulator
- Invent your own technical indicator
- Write a strategy that generates orders

** Types of funds
- ETF
  - Electronically Traded Fund
  - Buy/Sell like stocks
  - Baskets of stocks
  - Transparent

- Mutual Funds
  - Buy/Sell at end of day
  - Quarterly disclosure
  - Less transparent

- Hedge Funds
  - Buy/sell by agreement
  - No disclosure
  - Not transparent

** Liquidity and capitalizatio

Liquid
How easy you can buy and sell

Capitalization
How much is the company worth using the formula # Shares * Price


Symbols
Mutual Funds have 5 letters
ETFs have 4 or 3 letters

** Incentives for fund managers

Assets Under Management (AUM)

ETF
Expense Ratio
Percentage of AUM
0.01% (1 bip)
1.00% is high

Mutual Fund
Expense Ratio of AUM
0.5% to 3.00%

Hedge Funds
Two and Twenty
2% of AUM + 20% of profits

** Two and Twenty

Example
Fund's assets under management is 100,000,00
It grows to 115M
15% return

2% of 100M = 2M
20% of 15M = 3M
Total = 5M


Lately, Hedge Funds are typically lower. Example, 1 and 10

SAC -> 4 and 40

** How funds attract investors

Hedge Funds can only have 100 investors

Who?
- Individuals
- Instititutions
- Funds of funds

Why?
- Track record (typically 5 years of history)
- Simulation and story
- Good portfolio fit

** Hedge fund goals and metrics

Goals
- Beat a benchmark (SP500 for example)
- Absolute return (Long/Short)

Metrics
- Cumulative Return = (Val[-1]/Val[0]) - 1
- Volatility = daily_rets.std()   "standard deviation of daily returns"
- Risk/Reward or Sharpe Ratio =  sqrt(252) * mean(daily_rets - rf) / daily_rets.std         "Ratio risk to reward, Risk adjusted reward"
                                 sqrt(trading days of year) * reward / risk

** Computing inside a hedge fund

|-----------------------+-------------------+----------------+--------|
| Historical Price Data |                   | Orders         |        |
|                       |                   | orders_V.csv   |        |
|                       |                   |                |        |
|                       | Trading Algorithm |                | Market |
|                       | qstrader_X.py     |                |        |
|                       |                   |                |        |
| Target Portfolio      |                   | Live Portfolio |        |
|-----------------------+-------------------+----------------+--------|


The Trading Algorithm tries to get Live Portfolio to match a Target portfolio
You don't want to excute every thing at once else you might move the market against yourself


Computing the Target Portolio

|-----------------------+---+---------------------+---+------------------|
| N-day forcast         |   |                     |   |                  |
| forcast_X.h5          |   |                     |   |                  |
|                       |   |                     |   |                  |
|                       |   |                     |   |                  |
| Current Portfolio     |   | Portfolio Optimizer |   | Target Portfolio |
| portfolio_X.h5        |   | qsoptimizer_X.py    |   | portfolio_X.h5   |
|                       |   |                     |   |                  |
|                       |   |                     |   |                  |
| Historical Price Data |   |                     |   |                  |
|                       |   |                     |   |                  |
|                       |   |                     |   |                  |
|                       |   | Risk constraints    |   |                  |
|-----------------------+---+---------------------+---+------------------|

The forcast is generated possiblity with Machine Learning

|-----------------------+----------------------+---+---------------|
| Information Feed      |                      |   |               |
|                       |                      |   |               |
|                       | Forcasting Algorithm |   | N-day Forcast |
|                       | qsforcaster_X.py     |   | forcast_X.h5  |
|                       |                      |   |               |
| Historical Price Data |                      |   |               |
|                       |                      |   |               |
|-----------------------+----------------------+---+---------------|


Forcasting Algorithm is typically a model. Possibly using Machine Learning

* 02-02 - Market Mechanics
** What is in an order?

- Buy/Sell
- Symbol
- # Shares
- Limit or Market
- Price

The Order book
- Each exchange keeps and order book

|---------+--------+------|
| BID/ASK |  PRICE | SIZE |
|---------+--------+------|
| ASK     | 100.10 |  100 |
| ASK     | 100.05 |  500 |
| ASK     | 100.00 | 1000 |
| BID     |  99.95 |  100 |
| BID     |  99.90 |   50 |
| BID     |  99.85 |   50 |
|---------+--------+------|

BID == Buyer
ASK == Seller

ORDEr
BUY,IBM,100,LIMIT,99.95
SELL,IBM,1000,LIMIT,100

BUY,IBM,100,MARKET

** Hedge Fund

Exploiting market mechanics

Order book exploit
Colocate next to exchange and view the exchange's order book before remote buyers and sellers
Acting before orders that arrive later

Geographic Arbitrage Exploit
Exhanges are located far apart (NYSE and London)
Colocated in both exchanges with ultra-high speed connection between
Notice differences between the exchanges

** Additional Order Types

Exchanges
- Buy/Sell
- Market/Limit

Broker
Other types are implemented by the Broker
- Stop loss
  - Sell when stock falls to a specific value
- Stop gain
  - Sell when stock reaches
- Trailing stop
  - Stop loss that changes
- Selling short

** Short Selling

You borrow 100 shares and sell them to someone else and you get the selling price
You have the purchase amount but you owe the owner of the shares

You might have to give the shares back early

You are hoping that the value of the shares goes down
If it does then you can buy the shares for less, give back the shares you own and pocket the difference

** Short selling : Exit

You guy at 90 from someone else
Give back the 100 shares
Your profit is the original 100 price you paid less the 90 you paid to get the shares to give them back

** What can go wrong?

What if the price goes up?
You have to pay more to give back the shares. You lose that difference.

* 02-03 - What is a company is worth
** Why company  value matters

Value goes up over time (assumption)
Stock mark price oscollates around this value
 - If the price is higher than the value. sell
 - Buy if the price is below the value


- Intrisic value
  - Future dividends
  - How much will you get for ownership in the future

- Book value
  - Value of the company assets
  - Company assets

- Market cap
  - Value of the stock in the market and the shares outstanding
  - Market's opinion of the the company

** The Balch Bond

How much will the dollar worth in the future

** The value of a future dollar

Present Value = Future Value / (1 + Inerest Rate) ^ i

i = number of years

Example:

i = 1

US Govt Interest Rate = 1.%

= $1.00  / (1 + 0.01) = $0.99

Balch Bond Interest Rate = 5%

= $1.00 / (1 + 0.05) = $0.95

What about for today?
i is 0 to the Present Value is the Same as the Future Value

** Intrinsic Value

The interest is related to the risk of the company.
For example, the Balch Bond needed to raise it rate to attrach you over the Government bond

The Discount Rate is higher if you think the company is risky


Sum of equation for all i into the future

Equation:

Where n = 1 + IR

Sum FV / n ^ i where i = 1 to infinity

is

FV / (n -1)

which is

FV / DR or Future Value over the Discount Rate

Example, 

For a discount rate of 5% the present value is $1 / 0.05 => $20

FV is the dividend payment paid at regular intervals
DR is the what the risk of the stock translates to an interest that we should pay

** Dividend Example

Dividend = 2.00 / year
Discount Rate = 4%

2.00 / .04 =  50

** Book Value

"Total assets minus intangible assets and liabilities"

Intangible - brand, patent, etc


Total assets (fixed and intangile) - intangible assets - liabilites

** Market Capitalization

Market Cap = # Shares * Stock price

** Why information affects the stock price

Main mechanism that investors 

Example, negative news will reduce expectations of future dividends

** Would you buy this stock

Book Value
10 airplanes at $10M each = 100M
Brand name at $10M
$20M loan liability

BV = 80M
80,000,000

Intrinsic Value
$1M dividends/year with 5% DR
FV/DR = 1M/.05 = 20,000,000 = 20M
20,000,000

Market VAlue
1M shares outstanding
$75 stock
1M * 75 = 75M
75,000,000

** Summary
Instrinsic Value
- Future value of dividends
Book value
- Value of pieces
Market Cap
- Market's opinion of value

Strategies look for differences between the Book Value or Instrinsic Value and the Market Cap

- If Intrinsic value drops while Market cap stays high it might be signal to short
- If Dividends are going up and Market cap is low it might be signal to buy
- Book value provides a lowest price. When Market Cap approaches the book value it is unllikely to drop
  - if the market cap drops below book value it might be a signal to buy

* 02-04 - The Capital Asset Pricing Model
CAPM
1960s

The capital asset pricing model (CAPM) is a model that describes the
relationship between systematic risk and expected return for assets,
particularly stocks.

The CAPM was introduced by Jack Treynor (1961, 1962),[4] William
F. Sharpe (1964), John Lintner (1965a,b) and Jan Mossin (1966)
independently, building on the earlier work of Harry Markowitz on
diversification and modern portfolio theory. Sharpe, Markowitz and
Merton Miller jointly received the 1990 Nobel Memorial Prize in
Economics for this contribution to the field of financial economics.

- https://en.wikipedia.org/wiki/Capital_asset_pricing_model
- http://www.investopedia.com/articles/06/capm.asp
- http://www.investopedia.com/terms/c/capm.asp

** Definition of a portfolio

- Weighted set of assets
- wi : portion of funds in asset i
- Sum of Wi = 1.0

- 60%, 20%, 20%

- Shorting -20%
- Sow Sum of ABS of weights

Returns on a portfolio

Sum for each asset it's weight * return

Stock A = 75%
Stock B = -25%

Return A = 1%
Return B = -2%

= .75 * 1% + -.25% * -2%

= 75 + 1%
= .75 + .5
= 1.25%

** The market portfolio

|-------+-------|
| US    | SP500 |
| UK    | FTA   |
| Japan | TOPIX |
|-------+-------|


Cap weighted
The individual weight is set based on the market cap of the stock

Weight for individual  = Market Cap / Sum of all Market Caps

A capitalization-weighted (or "cap-weighted") index, also called a
market-value-weighted index is a stock market index whose components
are weighted according to the total market value of their outstanding
shares. Every day an individual stock's price changes and thereby
changes a stock index's value.
- http://www.investopedia.com/terms/c/capitalizationweightedindex.asp

To find the value of a cap-weighted index, an analyst should multiply
each constituent's market price by its total outstanding shares to
arrive at the total market value. Then, the proportion of this value
to the overall total market value of all the index components gives
the weight of the company in the index.

Read more: Capitalization-Weighted Index http://www.investopedia.com/terms/c/capitalizationweightedindex.asp#ixzz4eHgiaTpc 
Follow us: Investopedia on Facebook

For example, APPL and XOM are about 5% of the SP500

Market indexes are like the oceans with Sectors like the islands

** The CAPM equation

Return for an individual stock on a given day is Beta times the return on the market plus Alpha that particular stock on the given day.

A significant part of the return is based on the market (Beta).

A stock with a Beta a 1 means that the stock tracks with the market. 

The CAPM says that the expectation for Alpha is 0.

If you plot a stocks returns along with an index using a scatter chart.
Then regress to a line

The slope of the line is Beta and the offset from the index is Alpha

** Quiz
Correlated with SP500, ABC clearly has a greater slope than XYZ, therefore higher β.
It also has a larger Y-intercept (α).

** CAPM vs active management

Passive : buy index and hold
Active  : pick stocks

CAPM says Alpha is random and approaches 0
Active managers believe they can predict Alpha

** CAPM for portfolios

Beta for the portfolio * Return on the market + Alpha for the porfolio

** Quiz

You want a higher β in upward markets so that you can ride the surge, but a lower β in downward markets so you don't crash as much.

** Implications of CAPM

Beta * Return on the market + Alpha

Expected value of Alpha = 0
Only way to beat the market is to choose Beta

High Beta in up markets
Low Beta in down markets

Efficient Markets Hypothesis (EMH) says you can't redict the market

Which means you can beat the market

True? Some don't think so

** Arbitrage Pricing Theory (APT)

Stephen Ross (1976)

Maybe we need multiple Beta values due to exposures to different sectors

Examples, Betas for Finance, Tech, Manufacturing, etc

* 02-05 - How hedges funds use the CAPM
** Risks for hedge funds

The information edge they are looking for is market relative.  Meaning
they are looking for stocks which will go up more then the market when
the market goes up and ones that go down more than the market when the
market goes down.

** Two stock screnario

Predict long 1% and short 1%
With a market return of 0% we get
.5 + .5 = 1.00 or 1% return

** Quiz : Market goes up 10%
- NOTE: when we short the weight is negative

A: predict 1% over mkt with Ba = 1.0
B: predict -1% below mkt with Bb = 2.0

A: long 50
B: short 50


Ra = Ba * Rm  + Aa
   = 1.0 * 10% + 1%
   = 11%

   = 11% * 50.00 
   = $5.5

Rb = Bb * Rm + Ab
   = 2.0 * 10% + (-1%)
   = 20% - 1%
   = 19%

   = 19% * -50 (shorted against an upward market)
   = -9.50


Total
5.5 + -9.50 = -4.00
(.5 * 11) + (.5 * -19) = -4% 
5.5 - 9.5 = -4%

Same with market going down 10%


A: predict 1% over mkt with Ba = 1.0
B: predict -1% below mkt with Bb = 2.0

A: long 50
B: short 50


Ra = Ba * Rm  + Aa
   = 1.0 * -10% + 1%
   = -9%                     - market moved against us

   = -9% * 50.00 
   = -4.50

Rb = Bb * Rm + Ab
   = 2.0 * -10% + (-1%)
   = -20% - 1%
   = -21%                    - we shorted so we are with the market
   = 21%

   = -21% * -50   (shorted goes with the downward movement)
   = 10.50

Total
-4.50 + 10.50 = 6.0
(.5 * -9) + (.5 * 21) = 
-4.5 + 10.5 = 6%


** Two stock CAPM math

Return of a portfolio is the sum of the weights for each stock * the Beta * Return on the market + Alpha
Rp = SUM( Wi * (Bi * Ri + Ai))

If we short the stock the weight is negative

Example:

|----------+------------+----------|
| Wa = .5  | Aa = 1.0%  | Ba = 1.0 |
| Wb = -.5 | Ab = -1.0% | Bb = 2.0 |
|----------+------------+----------|

Rm = 10%

Rp = SUM( Wi * (Bi * Ri + Ai))
Rp = (WaBa + WbBb)Rm + WaAa + WbAb
Rp = (.5*1.0 + -5*2.0)* 10% + .5*1.0% + -.5*-1.0%
Rp = (.5 + -1)*Rm + .5 + .5
Rp = -.5*Rm + .5 + .5
Rp = -.5*Rm + 1%

Rm = 10%
Rp = -.5 * 10% + 1%
Rp = -5% + 1%
Rp = -4%

Note:
Rp = Beta * Rm + Alpha

Alpha is from information
We have no information about Rm

Can we find weights for A and B where their Beta becomes 0 
Then we have eliminated market risk


** Quiz : Find Wa and Wb so that market risk is minimized

|----------+------------|
| Ba = 1.0 | Aa = +1.0% |
| Bb = 2.0 | Ab = -1.0% |
|----------+------------|

Ba*Wa + Bb*Wb = 0
1.0*Wa + 2.0*Wb = 0
1.0 * Wa + 2.0 * -Wb = 0
1.0 * Wa = 2.0 Wb

Wa = 2.0 * Wb
abs(Wa) + abs(Wb) = 1

|----------+-----------|
| Wa = .66 | Wb = -.33 |
|----------+-----------|

** How does it work?

Rm = 10%

|----------+-----------|
| Wa = .66 | Wb = -.33 |
|----------+-----------|

A: predict 1% over mkt with Ba = 1.0
B: predict -1% below mkt with Bb = 2.0


Rp = (.66 * 1.0)Rm + (-.33 * 2.0)Rm + WaAa + WbAb
Rp = .66 * 1.0% + -.33* -1.0
Rp = 0 + WaAa + WbAb
Rp = .66*1% + -.33*-1
Rp = 1.0%

No guarentees on Betas continuing but still we've reduced market exposure

** CAPM for hedge funds summary

Assuming 
Information - Alpha i
Beta i

CAPM enables
Minimize market risk find Bp = 0
by finding the appropriate weights to accomplish this

* 02-06 - Technical Analysis
** Technical versus fundamental analysis
Fundamental - Aspects of company to value the company. Look for price less than value
Technical - Don't care about the value. Look for patterns or trends in a stocks price.

** Characterstics of Technical Analysis

- Historical price and volume only
- Comput statistics called indicators
- Indicators are heuristics

Some think:
Tehnical is more a trading approach than an investing approach

Why it might work
- There is information in the price
- Heuristics work

** Quiz: potential indicators

- moving average of price - Technical
- % change in volume - Technical
- Price/earnings ratio - Fundamental
- Intrinsic value - Fundamental

** When is technical analysis valuable

- Individual indicators are weak
  - More people are trading simple indicators
- Combinations stronger
- Look for contrasts (stock vs market)
- Shorter time periods

Trading horizon
milliseconds -> days -> years

Technical .... -> Fundamental

Fundamental is better for longer periods
Technical is more appropriate for shorter periods


Decision complexity increase for longer periods
Decision speed is faster for shorter time periods

High frequence trading. Fast, short decision, technical


Human. Longer periods. Insite driven

** Indictator - Momentum

- Change in price over time
- Positive or negative
- Strenth is the slope of the line (change in price over time)

- Visually
- Draw line between two price points for a given time period

- Quantitative
- Momentum[t] = price[t] / price [t-n] - 1
- n-day 5, 10, etc

- Typical Range: -.5 to +.5

** Indicator: Simple Moving Average (SMA)

- n-day window

- For a given day calculate the average price for the previous n days

- SMA lags the movement of the price


Two ways to use:
- Look for prices which cross the SMA line
  - Combine with strong momentum may be a signal

- Proxy for underlying value
   - If the price has a strong divergance from the SMA. May have an arbitrage opportunity

- Quantitatve
- Percent diff from price

SMA[t] = ( price[t] / price[t-n:t].mean() ) - 1

Typical range : -.50 to +.50

** Bollinger Bands

Low volitity use smaller excursion
High volotility use wider excurions

Use standard deviation
Say 2 degress

How to use
Lookg for cross from outside to the inside


BB[t] = (price[t] - SMA[t]) / 2 * std[t]

Typical Range: -1.0 to 1.0

** Quiz: Buy or Sell

- Excursion returning back through the bands are signals

- Excurions out of the band are not a signal

** Normalization

|----------+------+-----|
| SMA      |  -.5 |  .5 |
| Momentum |  -.5 |  .5 |
| BB       | -1.0 | 1.0 |
| PE ratio |    1 | 300 |
|----------+------+-----|

How to use in algorithms is the value are in different ranges.

Normalization
Move all into a range of -1 to 1

Normed = (Values - Mean) / Values.std()

** Wrap Up

- Heruristics
- Tucker's approach
  - There are other people's approach
- Don't start trading yet
  - Still more to learn
* 02-07 - Dealing with Data
** Overview
Primarily using historical price data

** How is data aggregated?

Tick data
    The price and volume of the transaction at a specific time

Consolidated data/ Grouped
    Minute, hour, day

Within the group
    Open - first value
    High - highest value in the the group
    Low - lowest value in the group
    Close - last value
    
    Volume - sum of all volume values for all ticks in the group


Time boundaries we are going to be working with are days

** Quiz : Price anomaly

Stock splits result in reduced price per unit.

For instance, say each stock unit is divided into two units, then the
value of each new unit drops to half.

** Stock splits

- Why?
- The price is too high

Less liquid for 100 shares which is a popular block for personal orders as well as options

Problem
How to trade and take into account the splits

Solution 
Adjusted close

Value of the company doesn't change. The number of shares changes
To account for the splits
Adjusted close or adjusted prices

Create a timeline of data working backwards
When you get to a split
    - Say a 2:1 price
    - Continue back and divide the price by 2

** Quiz : Split adjustment

- At the split, actual value
- Previous to the split, divide the price by 2 due to the 2:1 split

** Dividends

Date of 1.00 dividend
When announced the price of the stock will rise 1.00

Price will rise from 100 to 101 because everyone knows they'll have one share worth 100 plus 1.00

On the day of the dividend the price will fall to 100 because you'll get the 1.00 dividend in addition

** Adjusting for dividends

Strong price when the dividend pays out

Go back in time actual matches
When you get to a split you adjust the price the amount of the dividend (in precent)

Data will have both Actual and Adjusted
Assume for this course we are using Adjusted

Adjust for dividends and splits
Note: If you gather data in different years you may see different values

** Survivor bias

A biased strategy if you use today's stocks. Those that didn't survive are not in the data set.

If you use a list of stocks from the past some may not have survived and won't exist at the end of your range.

If you plot the results bewtween the two approaches and note the difference, this is the bias

Use survivor bias free data
Not usually free.
You won't have that false hope generated by having 

In finance, survivorship bias is the tendency for failed companies to
be excluded from performance studies because they no longer exist. It
often causes the results of studies to skew higher because only
companies which were successful enough to survive until the end of the
period are included.
- https://en.wikipedia.org/wiki/Survivorship_bias
* 02-08 - Efficient Markets Hypothesis
** Assumptions
- Large number of investors
- New information arrives randomly
- Prices adjust quickly
- Prices reflect all available information

** Origin of information
- Some sources organized from public to private (rough)

- Price/Volume
- Fundamental
- Exogenous
  - Information about the world that effects the company
  - relating to or developing from external factors.
  - Example, price of oil for an Airline stock
- Company insiders

** 3 Versions of the EMH
- From weak to strong

- Weak
  - Future prices cannot be predicted by analyzing historical prices
  - Leaves room for Fundamental

- Semi-strong: Prices adjust rapidly to new public information
  - Room for insider information

- Strong: Prices reflect all information public and private
  - If this is true then it is impossible to make money outside of a market portfolio

** Quiz: the EMH prohibits

|-------------+------+-------------+--------|
|             | Weak | Semi-Strong | Strong |
|-------------+------+-------------+--------|
| Technical   | -    | -           | -      |
| Fundamental |      | -           | -      |
| Insider     |      |             | -      |
|-------------+------+-------------+--------|

** Is the EMH correct?

Some Hedge Funds prove that it isn't

We've seen people make money from insider information (strong)

* 02-09 - The Fundamental Law of active portfolio managment
** Grinaold's Fundamental Law
- Performance
- Skill
- Breadth


performance = skill * sqrt(breadth)

Information Ratio (IR) = Information Coeeficient IC * Sqrt (Breadth)

Breadth is the number of trading opportunities

** The coin flipping casino

- Flip coins instead of stocks
- The coin is biased - like Alpha (0.51 heads)
- Uncertainty is like Beta

Betting
Even money betting
- Win: now have 2N
- Lose: now have 0

Casino
1000 tables
1000 tokens
Game runs in parallel

** Quiz: Which bet is better

Less risky
1 token on each of the 1000 tokens

** Quiz: Coin-Flip Casino: Reward

Expected return

- Single bet (Bet 1000 chips at once)

Notice -1000 (negative) for .49 percent chance of lossing
.51 * 1000 + .49 * -1000 =  
510 - 490 = 20

- Multiple Bets

1000(.51 * 1 + .49 * -1)
1000(.02) = 20

Expected return (reward) is the same
But, the risk is different

** Coin flip casino: Risk 1

- Lose it all

- Single bet 49%


- Muli-bet?
- Probability for the first table * the next * the next
- = .49 * .49 * .49 ... 
- .49 ^ 1000 
= a very small number

** Coin flip casino: Risk 2

Standard deviation of individual bets

One token per table
stdev(-1, 1, 1, 1, -1, ... -1) = 1.0


One 1000 token bet, 999 0 token bets on the other tables
stdev(1000, 0, 0, 0, 0, ..., 0) = 31.62
stdev(-1000, 0, 0, 0, 0, ..., 0) = 31.62

Key point the standard deviation or risk is much larger when we take a single bet

** Coin flip casino: Reward/isk
Just like Sharpe Ratio

- Single bet case

Reward (Expected Return) / Risk

20 / 31.62 = 0.63

Adjusted Risk reward is 0.63


- Multi bet case

Reward = 1000( .51*1 + .49* -1) = 20
Risk = std(1, -1, 1, -1, ...) = 1


Taking potential risk into account makes such a difference, doesn't it?

** Coin flip casino observation

Single 1000 token bet has a Sharpe rati0oof .63

Multiple 1000 token bets has a Sharpe ratio of 20

SRmulti = 20
SRsingle = .63

20 = 63 * sqrt(1000)

SRmulti = SRsingle * sqrt(bets)

Perfformance = Skill * sqrt(breadth)



